{
"code" : "en",
"name" : "English",
"translator" : "",
"lang" : "Change language:",
"version" : "version",
"help" : "Help",
"about" : "About",
"share" : "Share",
"sharewith" : "Share it with",
"switchtext" : "switch to __WAVELENGTH__ view of the sky",
"search" : "search",
"press" : "Press __KEY__",
"close" : "Close",
"closedesc" : "click to close",
"switchannotation" : " show or hide __ANNOTATION__",
"showhide" : "show or hide all screen furniture (except the credit line)",
"up" : "higher energy (reduce the wavelength)",
"down" : "lower energy (increase the wavelength)",
"zoomin" : "zoom in",
"zoomout" : "zoom out",
"nozoomin" : "Can't zoom in any more",
"nozoomout" : "Can't zoom out any more",
"url" : "The URL for this view is:",
"gal" : "http://en.wikipedia.org/wiki/Galactic_coordinate_system",
"galcoord" : "Galactic Coordinates",
"eq" : "http://en.wikipedia.org/wiki/Equatorial_coordinate_system",
"eqcoord" : "Equatorial Coordinates",
"gamma" : "Gamma ray",
"xray" : "X-ray",
"optical" : "Visible",
"halpha" : "Hydrogen &alpha;",
"farir" : "Far-Infrared",
"nearir" : "Near-Infrared",
"microwave" : "Microwave",
"radio" : "Radio",
"labels" : "Labels"
}
